en:
  contentDir: content/en
  languageName: English
  weight: 1
  params:
    label: English
    locale: en-US

fr:
  contentDir: content/fr
  languageName: Français
  weight: 2
  params:
    label: Français
    locale: fr-FR